"use client";
import { useCallback, useState } from "react";
import Link from "next/link";
import Image from "next/image";
import { Activity, ArrowLeft, ExternalLink, FileKey2, LoaderCircle, Plus, RefreshCw, ScanSearch, ShieldAlert, Wallet, Workflow } from "lucide-react";
import { connectWallet, contractAddress, explorerUrl, readContract, unwrap, writeContract } from "@/lib/genlayer";
import { decodeReturnedId } from "@/lib/receipt";

type Totals={agreements:number;obligations:number;checkpoints:number};
type Notice={tone:"ok"|"error"|"pending";text:string};

export default function Monitor(){
  const [wallet,setWallet]=useState("");const[totals,setTotals]=useState<Totals|null>(null);const[notice,setNotice]=useState<Notice|null>(null);
  const [agreement,setAgreement]=useState({counterparty:"",name:"Cloud Services Agreement",version:"v1",digest:""});
  const [obligation,setObligation]=useState({agreementId:"",key:"uptime-core",kind:"UPTIME",title:"Commercially reasonable uptime",requirement:"Maintain commercially reasonable availability for the bound service during every sealed observation window.",origin:"https://example.com",url:"https://example.com/status",marker:"service status",cadence:"86400",window:"3600"});
  const [checkpoint,setCheckpoint]=useState({obligationId:"",checkpointId:""});
  const busy=notice?.tone==="pending";
  const connect=useCallback(async()=>{const result=await connectWallet();if(result.success)setWallet(String(result.data));else setNotice({tone:"error",text:result.error||"Wallet connection failed."});},[]);
  const sync=useCallback(async()=>{setNotice({tone:"pending",text:"Reading authoritative contract state…"});const result=await readContract("get_totals");if(!result.success){setNotice({tone:"error",text:result.error||"Read failed."});return;}const parsed=unwrap<Totals>(result.data);if(!parsed){setNotice({tone:"error",text:"Contract returned an unreadable totals payload."});return;}setTotals(parsed);setNotice({tone:"ok",text:"Contract state synchronized."});},[]);
  async function submit(label:string,method:string,args:unknown[],onId?:(id:string)=>void){setNotice({tone:"pending",text:`${label}: waiting for finality and consensus…`});const result=await writeContract(method,args);if(!result.success){setNotice({tone:"error",text:result.error||`${label} failed.`});return;}try{if(onId){const id=decodeReturnedId(result.transaction,result.receipt,result.data);onId(id);}await sync();setNotice({tone:"ok",text:`${label} finalized and reconciled with contract readback.${result.hash?` Tx ${result.hash.slice(0,10)}…`:""}`});}catch(error){setNotice({tone:"error",text:error instanceof Error?error.message:"Finalized return could not be verified."});}}
  return <main className="console"><header><Link className="brand" href="/"><Image className="brandLogo" src="/clausepilot-logo.jpg" alt="" width={36} height={36} priority/>ClausePilot</Link><Link className="back" href="/"><ArrowLeft/> Product</Link><div className="consoleActions"><a href={explorerUrl()} target="_blank" aria-label="Open explorer"><ExternalLink/></a><button onClick={connect}><Wallet/>{wallet?`${wallet.slice(0,6)}…${wallet.slice(-4)}`:"Connect wallet"}</button></div></header>
    <section className="consoleHero"><div><small>OBLIGATION CONTROL PLANE</small><h1>Observe what the agreement requires.</h1><p>Every write waits for finality, consensus and authoritative readback.</p></div><button className="sync" onClick={sync} disabled={busy}><RefreshCw/> Sync contract</button></section>
    <section className="ledger"><div><small>ACTIVE CONTRACT</small><b>{contractAddress()||"NOT CONFIGURED"}</b></div><div><small>AGREEMENTS</small><b>{totals?.agreements??"—"}</b></div><div><small>OBLIGATIONS</small><b>{totals?.obligations??"—"}</b></div><div><small>CHECKPOINTS</small><b>{totals?.checkpoints??"—"}</b></div></section>
    {notice&&<div className={`notice ${notice.tone}`}>{notice.tone==="pending"?<LoaderCircle className="spin"/>:notice.tone==="error"?<ShieldAlert/>:<Activity/>}<span>{notice.text}</span></div>}
    <section className="howWorks"><div className="howIntro"><small>HOW IT WORKS</small><h2>Consent, configure, observe.</h2><p>Complete the cards from left to right. ClausePilot reads every returned ID from the finalized receipt and places it into the next step automatically.</p></div><div className="howSteps"><article><span>01</span><FileKey2/><div><b>Register and accept</b><p>The owner binds the clause digest; the named counterparty accepts that exact agreement record.</p></div></article><article><span>02</span><Workflow/><div><b>Add a bounded obligation</b><p>Choose one semantic requirement, its authority origin, exact evidence URL and checkpoint schedule.</p></div></article><article><span>03</span><ScanSearch/><div><b>Open and assess</b><p>Open a due checkpoint, then validators independently fetch evidence and reconcile the standing.</p></div></article></div><div className="howHint"><b>Result guide</b><span><i className="satisfied"/> SATISFIED</span><span><i className="risk"/> AT RISK</span><span><i className="breach"/> BREACHED</span><span><i className="unresolved"/> UNRESOLVED</span></div></section>
    <section className="workGrid"><article className="workCard"><div className="cardTitle"><span>01</span><div><small>AGREEMENT REGISTRY</small><h2>Bind and accept the agreement</h2></div></div><label>Counterparty wallet<input value={agreement.counterparty} onChange={e=>setAgreement({...agreement,counterparty:e.target.value})} placeholder="0x…"/></label><div className="two"><label>Agreement name<input value={agreement.name} onChange={e=>setAgreement({...agreement,name:e.target.value})}/></label><label>Version<input value={agreement.version} onChange={e=>setAgreement({...agreement,version:e.target.value})}/></label></div><label>Clause bundle SHA-256<input value={agreement.digest} onChange={e=>setAgreement({...agreement,digest:e.target.value})} placeholder="64 lowercase hex characters"/></label><button className="primary wide" disabled={busy} onClick={()=>submit("Register agreement","register_agreement",[agreement.counterparty,agreement.name,agreement.version,agreement.digest],id=>setObligation({...obligation,agreementId:id}))}><Plus/> Register agreement</button><div className="consentBox"><div><b>Counterparty consent</b><p>Switch to the named counterparty wallet, verify the agreement ID and accept before adding obligations.</p></div><label>Agreement ID<input value={obligation.agreementId} onChange={e=>setObligation({...obligation,agreementId:e.target.value})}/></label><button className="secondary" disabled={busy||!obligation.agreementId} onClick={()=>submit("Accept agreement","accept_agreement",[obligation.agreementId])}>Accept agreement</button></div></article>
      <article className="workCard"><div className="cardTitle"><span>02</span><div><small>BOUNDED OBLIGATION</small><h2>Approve source and schedule</h2></div></div><div className="two"><label>Agreement ID<input value={obligation.agreementId} onChange={e=>setObligation({...obligation,agreementId:e.target.value})}/></label><label>Obligation key<input value={obligation.key} onChange={e=>setObligation({...obligation,key:e.target.value})}/></label></div><div className="two"><label>Kind<select value={obligation.kind} onChange={e=>setObligation({...obligation,kind:e.target.value})}><option>UPTIME</option><option>INCIDENT_NOTICE</option><option>CERTIFICATION</option></select></label><label>Title<input value={obligation.title} onChange={e=>setObligation({...obligation,title:e.target.value})}/></label></div><label>Bounded requirement<textarea value={obligation.requirement} onChange={e=>setObligation({...obligation,requirement:e.target.value})}/></label><div className="two"><label>Authority origin<input value={obligation.origin} onChange={e=>setObligation({...obligation,origin:e.target.value})}/></label><label>Exact evidence URL<input value={obligation.url} onChange={e=>setObligation({...obligation,url:e.target.value})}/></label></div><label>Required object marker<input value={obligation.marker} onChange={e=>setObligation({...obligation,marker:e.target.value})}/></label><div className="two"><label>Cadence seconds<input value={obligation.cadence} onChange={e=>setObligation({...obligation,cadence:e.target.value})}/></label><label>Window seconds<input value={obligation.window} onChange={e=>setObligation({...obligation,window:e.target.value})}/></label></div><button className="primary wide" disabled={busy} onClick={()=>submit("Add obligation","add_obligation",[obligation.agreementId,obligation.key,obligation.kind,obligation.title,obligation.requirement,obligation.origin,obligation.url,obligation.marker,Number(obligation.cadence),Number(obligation.window)],id=>setCheckpoint({...checkpoint,obligationId:id}))}><Plus/> Add obligation</button></article>
      <article className="workCard full"><div className="cardTitle"><span>03</span><div><small>LIVE CHECKPOINT</small><h2>Observe, judge, reconcile</h2></div></div><div className="checkpointRow"><label>Obligation ID<input value={checkpoint.obligationId} onChange={e=>setCheckpoint({...checkpoint,obligationId:e.target.value})}/></label><button className="secondary" disabled={busy} onClick={()=>submit("Open checkpoint","open_due_checkpoint",[checkpoint.obligationId],id=>setCheckpoint({...checkpoint,checkpointId:id}))}>Open due checkpoint</button><label>Checkpoint ID<input value={checkpoint.checkpointId} onChange={e=>setCheckpoint({...checkpoint,checkpointId:e.target.value})}/></label><button className="primary" disabled={busy} onClick={()=>submit("Assess checkpoint","assess_checkpoint",[checkpoint.checkpointId])}>Run AI consensus</button></div><div className="guardrail"><ShieldAlert/><p><b>Guardrail:</b> missing, mismatched or unavailable evidence becomes <code>UNRESOLVED</code>. ClausePilot does not infer legal liability or calculate damages.</p></div></article></section>
  </main>;
}
